### ISSUE TITLE
SilkService unable for load YaraSharp.dll

### ISSUE THREAD

**Issue by hxnoyd** [fireeye/SilkETW#11]
I'm trying to setup SilkService 0.8 in a Eval MS Edge VM (Windows10 1809). When starting the service throws the following error:
```
Service cannot be started. System.IO.FileNotFoundException: Could not load file or assembly 'YaraSharp.dll' or one of its dependencies. The specified module could not be found.
File name: 'YaraSharp.dll'
   at SilkService.SilkParameters.ValidateCollectorParameters(List`1 Collectors)
   at SilkService.SilkService.OnStart(String[] args) in C:\Users\b33f\Desktop\SilkService\SilkService.cs:line 30
   at System.ServiceProcess.ServiceBase.ServiceQueuedMainCallback(Object state)
```
I'm using the pre build 0.8 package from releases.

Any suggestion on what might be causing this?
Thanks in advance!
RD

**Comment by hxnoyd** [comment]
Looks like I was missing the vc2015_redist.x86.exe req. My bad :)
